server:
  port: 8888

# Spring Cloud  Config 配置
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/sunsiguang/cloud-config-server.git  # github 上的仓库名字
          uri:  https://gitee.com/sunsgkv/cloud-config-server.git             # gitee 上仓库暂时需要 public
          search-paths:    #搜索目录
            - cloud-config-server
#          force-pull: true
#          username: configserver
#          password: DZ4anb8c
      label: master


# 客户端Eureka 配置
eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    #服务端是否自己注册自己，服务端是false , 客户端是true
    register-with-eureka: true
    #是否去检索服务
    fetch-registry: true
    service-url:
      #defaultZone:  localhost:8761/eureka/    #单机配置
      defaultZone:  http://eureka8761.com:8761/eureka/