server:
  port: 8888

# Spring Cloud  Config 配置
spring:
  application:
    name: cloud-config-server

  zipkin: # 增加 链路追踪 配置类  , # zipkin的服务地址
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率，介于0到1之间，1表示全部采集
      probability: 1

  cloud:
    config:
      server:
        git:
#          uri: https://github.com/sunsiguang/cloud-config-server.git  # github 上的仓库名字
          uri:  https://gitee.com/sunsgkv/cloud-config-server.git             # gitee 上仓库暂时需要 public
          search-paths:    #搜索目录
            - cloud-config-server
#          force-pull: true
#          username: configserver
#          password: DZ4anb8c
          label: master
          default-label: master   # 添加不会报错，但不影响使用

  # 添加 rabbitMQ 配置支持，用于BUS 消息总线推送，注意：Spring.rabbitmq.***
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest


# 客户端Eureka 配置
eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    #服务端是否自己注册自己，服务端是false , 客户端是true
    register-with-eureka: true
    #是否去检索服务
    fetch-registry: true
    service-url:
      #defaultZone:  localhost:8761/eureka/    #单机配置
      defaultZone:  http://eureka8761.com:8761/eureka/



# 关键步骤 ： rabbitMQ 相关配置，暴露bus 刷新配置的端点，利用rabbitMQ 和  actuator  ( Config Server 端配置)
management:
    endpoints:  # 暴露bus 刷新配置的端点
        web:
            exposure:
                include:  bus-refresh

# For tests
logging.level.org.springframework.cloud.sleuth: DEBUG

