server:
  port: 8006
spring:
  application:
    name: cloud-payment-service  #服务名

  zipkin: # 增加 链路追踪 配置类  , # zipkin的服务地址
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率，介于0到1之间，1表示全部采集
      probability: 1

  #注册Consul中心地址
  cloud:
    consul:
      host: localhost
      port: 8500   #默认端口
      discovery:
        #hostname:127.0.0.1
        service-name: ${spring.application.name}

# For tests
logging.level.org.springframework.cloud.sleuth: DEBUG