server:
  port: 81
spring:
  application:
    name: cloud-order-service  #服务名

  #注册Consul中心地址
  cloud:
    consul:
      host: localhost
      port: 8500   #默认端口
      discovery:
        #hostname:127.0.0.1
        service-name: ${spring.application.name}