server:
  port: 8001
spring:
  application:
    name: cloud-payment8001

  datasource:
    url: jdbc:mysql://192.168.231.144:3306/test
    username: mantisdb
    password: mantisdb
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      aop-patterns:
      filters: stal,wall
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      web-stat-filter:
        enabled: true

