server:
   port:  88
spring:
  application:
      name: data-jpa
  datasource:
    url: jdbc:mysql://192.168.231.144:3306/test?charset=utf8
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
     show-sql: true   # sql 打印
     properties:
       hibernate:
         format_sql: true  # 格式化

logging:
  level:
    org.hibernate.SQL: info  # debug 也会输出一条SQL语句
    org.hibernate.type.descriptor.sql.BasicBinder: trace
