server:
  port: 8762

spring:
  application:
    name: cloud-eureka-server

eureka:
  instance:
    hostname: eureka8762.com     #eureka 服务端的实例名称 , 对应的hosts 目录下的主机名

  client:
    #服务端是否自己注册自己，服务端是false , 客户端是true
    register-with-eureka: false
    #是否去检索服务
    fetch-registry: false
    service-url:
      #集群配置
      #defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka2:8862/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka3:8863/eureka/
      #defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:7001/eureka/
      # 集群原理 : 互相注册，相互守望
      defaultZone:  http://eureka8761.com:8761/eureka/, http://eureka8762.com:8762/eureka/, http://eureka8763.com:8763/eureka/

      ##Host 主机配置域名如下：
# 127.0.0.1 eureka8761.com
# 127.0.0.1 eureka8762.com
# 127.0.0.1 eureka8763.com

