server:
   port:  9001

spring:
    application:
         name: cloud-payment-service  #服务名
    cloud:
         nacos:
            discovery:
                server-addr: 127.0.0.1:8848

management:
    endpoints:
        web:
            exposure:
                 include: '*'